### ISSUE TITLE
Generate UI wireframe

### ISSUE THREAD

**Issue by aelizj** [olgashi/request_bin#11]
For the 'Create bin' and 'Event log' views, map out where the components will go and upload a link/document/picture here.

**Comment by donald-p-redding** [comment]
![Image](https://user-images.githubusercontent.com/71610961/171315236-81302524-b27c-4152-86f9-ce92ffb51c9a.png)

**Comment by donald-p-redding** [comment]
very basic at the moment. But it's something.
